spring.application.name=gateway-service
server.port=9999
spring.cloud.discovery.enabled=true

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}

# Utilisation des clés recommandées par ton log
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

# FIX CRITIQUE : Voici les clés exactes à utiliser en 3.5
 spring.cloud.gateway.server.webflux.httpclient.pool.max-idle-time=10000
 spring.cloud.gateway.server.webflux.httpclient.connect-timeout=5000
 spring.cloud.gateway.server.webflux.httpclient.response-timeout=10s