spring.application.name=ebank-bot
spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=gpt-4o
spring.cloud.discovery.enabled=true
spring.cloud.config.enabled=false
server.port=8058

spring.ai.mcp.client.streamable-http.connections.customer.url=http://localhost:8056/mcp
