spring.application.name=ebank-bot
spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=gpt-4o
spring.cloud.discovery.enabled=true
spring.cloud.config.enabled=false
server.port=8058